openapi: 3.1.0
info:
  title: Yurtle API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /tasks:
    post:
      summary: Get All My Tasks
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples: {}
        '400':
          description: Missing Required Parameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                deadline:
                  type:
                    - string
                    - 'null'
                  format: date
              required:
                - name
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
    parameters: []
    get:
      summary: ''
      operationId: get-tasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  total_count:
                    type: number
                required:
                  - tasks
                  - total_count
      description: Fetch all my tasks
  '/tasks/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get Task
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: Not Found
      operationId: get-task
      description: Retrieve the information of the task with the matching task ID.
    patch:
      summary: Update User Information
      operationId: patch-task
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: Not Found
      description: Update the information of an existing task.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                deadline:
                  type:
                    - string
                    - 'null'
                  format: date
            examples: {}
        description: Patch user properties to update.
  '/tasks/{id}/complete':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: Complete Task
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Not Found
      operationId: complete-task
      requestBody:
        content:
          application/json:
            schema:
              type: object
      description: Complete task
components:
  schemas:
    Task:
      title: Task
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        name:
          type: string
        completed:
          type: boolean
        deadline:
          type:
            - string
            - 'null'
          format: date
        created_at:
          type: string
          format: date-time
          description: The date that the user was created.
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - id
        - name
        - completed
        - deadline
        - created_at
        - updated_at
